import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Registry, ToolInfo } from "../client.ts";
import { findProjectRoot } from "../config.ts";
import { EXIT } from "../output.ts";
import { dcomposeRoot, dcomposeTypesEntry, projectDcomposeDir } from "../paths.ts";
import { generateTypes, readHash, toolsHash } from "../typegen.ts";

export interface TypesOptions {
  server?: string[];
  force?: boolean;
  out?: string;
  print?: boolean;
}

export async function typesCommand(registry: Registry, opts: TypesOptions): Promise<number> {
  const projectRoot = findProjectRoot();
  const dir = projectDcomposeDir(projectRoot);
  const outPath = opts.out ?? join(dir, "types", "mcp.d.ts");
  const err = (s: string) => process.stderr.write(s + "\n");

  const servers = opts.server?.length ? opts.server.map((n) => registry.get(n)) : registry.all();
  const byServer = new Map<string, ToolInfo[]>();
  let failures = 0;
  await Promise.all(
    servers.map(async (s) => {
      try {
        byServer.set(s.name, await s.listTools());
      } catch (e) {
        failures++;
        err(`dcompose: ${(e as Error).message}`);
      }
    }),
  );
  if (byServer.size === 0) return EXIT.CONFIG;

  const hash = toolsHash(byServer);
  if (!opts.force && !opts.print && existsSync(outPath) && readHash(readFileSync(outPath, "utf8")) === hash) {
    err(`types up to date (${relative(process.cwd(), outPath) || outPath}); use --force to regenerate`);
    writeTsconfig(dir, projectRoot);
    return failures ? EXIT.CONFIG : EXIT.OK;
  }

  const source = await generateTypes(byServer);
  if (opts.print) {
    process.stdout.write(source);
    return EXIT.OK;
  }

  mkdirSync(join(dir, "types"), { recursive: true });
  writeFileSync(outPath, source, "utf8");
  writeTsconfig(dir, projectRoot);

  const total = [...byServer.values()].reduce((n, t) => n + t.length, 0);
  const withOut = [...byServer.values()].flat().filter((t) => t.outputSchema).length;
  err(
    `wrote ${relative(process.cwd(), outPath) || outPath}: ${byServer.size} server${byServer.size === 1 ? "" : "s"}, ${total} tools (${withOut} with output schemas)`,
  );
  return failures ? EXIT.CONFIG : EXIT.OK;
}

/**
 * `.dcompose/tsconfig.json` makes `import type { Ctx } from "dcompose"` resolve to this
 * install of dcompose for editors and `dcompose check`, with no runtime dependency
 * (type-only imports are erased by Node's type stripping).
 */
export function writeTsconfig(dir: string, projectRoot: string): void {
  const path = join(dir, "tsconfig.json");
  const root = dcomposeRoot();
  const config = {
    "//": "Generated by `dcompose types`. Machine-specific; regenerate rather than edit.",
    compilerOptions: {
      target: "ES2023",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      rewriteRelativeImportExtensions: true,
      baseUrl: ".",
      paths: { dcompose: [toPosix(dcomposeTypesEntry())] },
      typeRoots: [toPosix(join(projectRoot, "node_modules", "@types")), toPosix(join(root, "node_modules", "@types"))],
      types: ["node"],
    },
    include: ["scripts/**/*", "types/**/*"],
  };
  mkdirSync(dir, { recursive: true });
  writeFileSync(path, JSON.stringify(config, null, 2) + "\n", "utf8");
}

function toPosix(p: string): string {
  return p.replace(/\\/g, "/");
}
