import { createHash } from "node:crypto";
import { compile } from "json-schema-to-typescript";
import type { ToolInfo } from "./client.ts";

/**
 * Emit a TypeScript declaration file that augments `dcompose`'s `McpServers` so `ctx.mcp` is
 * strictly typed. Input schemas come from `inputSchema`; return types from `outputSchema` when
 * a server provides one, otherwise `any`.
 */
export async function generateTypes(byServer: Map<string, ToolInfo[]>): Promise<string> {
  const chunks: string[] = [];
  const augment: string[] = [];

  for (const [server, tools] of [...byServer.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const ifaceName = pascal(server);
    const members: string[] = [];
    const rawMembers: string[] = [];

    for (const t of [...tools].sort((a, b) => a.name.localeCompare(b.name))) {
      const base = `${ifaceName}_${ident(t.name)}`;
      const inputName = `${base}_Input`;
      const outputName = `${base}_Output`;

      chunks.push(await compileSchema(t.inputSchema, inputName));
      let outType = "any";
      if (t.outputSchema) {
        chunks.push(await compileSchema(t.outputSchema, outputName, "output"));
        outType = outputName;
      }

      const doc = jsdoc(t);
      const argOptional = isEmptyObjectSchema(t.inputSchema) || !hasRequired(t.inputSchema) ? "?" : "";
      const key = /^[A-Za-z_$][\w$]*$/.test(t.name) ? t.name : JSON.stringify(t.name);
      members.push(`${doc}  ${key}(args${argOptional}: ${inputName}): Promise<${outType}>;`);
      rawMembers.push(`    ${key}(args${argOptional}: ${inputName}): Promise<import("dcompose").RawToolResult>;`);
    }

    chunks.push(
      [
        `export interface ${ifaceName} {`,
        ...members,
        `  /** Unparsed MCP result envelopes. */`,
        `  raw: {`,
        ...rawMembers,
        `  };`,
        `}`,
        ``,
      ].join("\n"),
    );
    augment.push(`    ${/^[A-Za-z_$][\w$]*$/.test(server) ? server : JSON.stringify(server)}: ${ifaceName};`);
  }

  const header = [
    `// Generated by \`dcompose types\` on ${new Date().toISOString()}. Do not edit.`,
    `// hash: ${toolsHash(byServer)}`,
    `/* eslint-disable */`,
    ``,
    `declare module "dcompose" {`,
    `  interface McpServers {`,
    ...augment,
    `  }`,
    `}`,
    ``,
  ].join("\n");

  return header + chunks.join("\n");
}

export function toolsHash(byServer: Map<string, ToolInfo[]>): string {
  const h = createHash("sha256");
  for (const [server, tools] of [...byServer.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    h.update(server);
    for (const t of [...tools].sort((a, b) => a.name.localeCompare(b.name))) {
      h.update(t.name);
      h.update(JSON.stringify(t.inputSchema ?? null));
      h.update(JSON.stringify(t.outputSchema ?? null));
    }
  }
  return h.digest("hex").slice(0, 16);
}

/** Read the hash line back out of a previously generated file. */
export function readHash(contents: string): string | null {
  return /^\/\/ hash: ([0-9a-f]+)$/m.exec(contents)?.[1] ?? null;
}

async function compileSchema(schema: unknown, name: string, kind: "input" | "output" = "input"): Promise<string> {
  const cleaned = stripTitles(structuredClone(schema ?? { type: "object" })) as Record<string, unknown>;
  if (cleaned.type === undefined && cleaned.properties) cleaned.type = "object";
  try {
    const out = await compile(cleaned as any, name, {
      bannerComment: "",
      // Inputs are strict: an unknown argument is a real bug. Outputs are open: servers routinely
      // declare a subset of what they return, so undeclared fields type as unknown instead of erroring.
      additionalProperties: kind === "output",
      format: false,
      declareExternallyReferenced: true,
      unreachableDefinitions: false,
      ignoreMinAndMaxItems: true,
    });
    // The generator re-cases the requested name (e.g. Foo_bar_Input → FooBar_Input). Pin it back
    // so the method signatures reference a declaration that actually exists.
    const decls = [...out.matchAll(/^export (?:interface|type) ([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]!);
    if (decls.length === 0)
      return `export type ${name} = Record<string, unknown>; // generator produced no declaration\n`;
    // Hoisted helpers (from $defs) get a per-tool prefix so `ServiceReference` from one tool cannot
    // merge with a differently-shaped `ServiceReference` from another.
    // Output objects are open (see additionalProperties above); make the extras `any` rather than
    // `unknown` so `seen[i.id]` and similar just work on fields the server forgot to declare.
    let fixed = kind === "output" ? out.replace(/\[k: string\]: unknown/g, "[k: string]: any") : out;
    for (const d of decls.slice(1)) fixed = fixed.replace(new RegExp(`\\b${d}\\b`, "g"), `${name}_${d}`);
    if (decls[0] !== name) fixed = fixed.replace(new RegExp(`\\b${decls[0]}\\b`, "g"), name);
    return fixed;
  } catch (e) {
    return `/** schema could not be converted: ${(e as Error).message.replace(/\*\//g, "* /")} */\nexport type ${name} = Record<string, unknown>;\n`;
  }
}

/** Nested `title`s make the generator hoist named interfaces that collide across tools. */
function stripTitles(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(stripTitles);
  if (node && typeof node === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === "title" || k === "$id" || k === "id") continue;
      out[k] = stripTitles(v);
    }
    return out;
  }
  return node;
}

function isEmptyObjectSchema(s: unknown): boolean {
  if (!s || typeof s !== "object") return true;
  const o = s as { properties?: Record<string, unknown>; required?: string[] };
  return !o.properties || Object.keys(o.properties).length === 0;
}

function hasRequired(s: unknown): boolean {
  const o = s as { required?: string[] } | undefined;
  return Array.isArray(o?.required) && o.required.length > 0;
}

function jsdoc(t: ToolInfo): string {
  const lines: string[] = [];
  if (t.description) lines.push(...t.description.trim().split(/\r?\n/));
  const hints: string[] = [];
  if (t.readOnly) hints.push("read-only");
  if (t.annotations?.destructiveHint) hints.push("destructive");
  if (t.annotations?.idempotentHint) hints.push("idempotent");
  if (hints.length) lines.push(`@hints ${hints.join(", ")}`);
  if (!t.outputSchema) lines.push("@returns any — server provides no outputSchema; inspect with `dcompose call`");
  if (lines.length === 0) return "";
  return "  /**\n" + lines.map((l) => `   * ${l.replace(/\*\//g, "* /")}`).join("\n") + "\n   */\n";
}

function pascal(s: string): string {
  const p = s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");
  return /^[A-Za-z_$]/.test(p) ? p : `S${p}`;
}

function ident(s: string): string {
  const i = s.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(i) ? i : `_${i}`;
}
